apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts: 
    - image: kr8sdemo/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: kr8sdemo/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "*.js"
            dest: .
    - image: kr8sdemo/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "*.js"
            dest: .
    - image: kr8sdemo/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "*.js"
            dest: .
    - image: kr8sdemo/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "*.js"
            dest: .
    - image: kr8sdemo/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "*.js"
            dest: .

            